services:
  ##################### POSTGRES PGADMIN############################
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE: ${DATABASE}
    ports:
      - "${HOST_POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - ./docker_init/postgres_init:/docker-entrypoint-initdb.d
      - ./docker_volume/postgres_data:/var/lib/postgresql/data
    logging:
      driver: none
    networks:
      - netexchange
  # pgadmin:
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
  #     PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
  #     PGADMIN_CONFIG_SERVER_MODE: "False"
  #     PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
  #   ports:
  #     - "${HOST_PGADMIN_PORT}:${PGADMIN_PORT}"
  #   command: ["./wait-for-it.sh", "postgres:5432", "--", "pgadmin4"]
  #   volumes:
  #     - ./docker_init/pgadmin_init/servers.json:/pgadmin4/servers.json
  #     - ./docker_init/pgadmin_init/wait-for-it.sh:/wait-for-it.sh
  #     - ./docker_init/pgadmin_init/.pgpass:/.pgpass
  #   user: "root"
  #   logging:
  #     driver: none
  #   networks:
  #     - netexchange
  # perfect_server:
  #   build:
  #     context: ./perfect_server
  #     dockerfile: Dockerfile
  #   environment:
  #     PREFECT_API_DATABASE_CONNECTION_URL: "postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/prefect"
  #     PREFECT_SERVER_API_HOST: "0.0.0.0"
  #     PREFECT_API_URL: "http://0.0.0.0:${PERFECT_PORT}/api"
  #     POSTGRES_HOST: "postgres"
  #     POSTGRES_PORT: "5432"
  #   volumes:
  #     - ./perfect_server:/app
  #   ports:
  #     - "${PERFECT_PORT}:${PERFECT_PORT}"
  #   depends_on:
  #     - postgres
  #   networks:
  #     - netexchange
    # logging:
    #   driver: none

  fast_api:
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      DATABASE: ${DATABASE}
    ports:
      - "${HOST_FAST_API_PORT}:${FAST_API_PORT}"
    volumes:
      - ./fastapi:/app
    # logging:
    #   driver: none
    depends_on:
      - postgres
    networks:
      - netexchange
  # scheduler:
  #   build:
  #     context: ./scheduler
  #     dockerfile: Dockerfile
  #   environment:
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_HOST: ${POSTGRES_HOST}
  #     POSTGRES_PORT: ${POSTGRES_PORT}
  #     DATABASE: ${DATABASE}
  #     PREFECT_API_URL: "http://perfect_server:4200/api"
  #     PREFECT_HOST: "perfect_server"
  #     PREFECT_PORT: ${PERFECT_PORT}
  #   volumes:
  #     - ./scheduler:/app
  #   # logging:
  #   #   driver: none
  #   depends_on:
  #     - perfect_server
  #     - postgres
  #   networks:
  #     - netexchange
networks:
  netexchange:
    driver: bridge
